export const COUNT_BUN_UP = 'COUNT_BUN_UP';
export const COUNT_BUN_DOWN = 'COUNT_BUN_DOWN';
export const COUNT_INGREDIENT_UP = 'COUNT_INGREDIENT_UP';
export const COUNT_INGREDIENT_DOWN = 'COUNT_INGREDIENT_DOWN';
export const DELETE_COUNT = 'DELETE_COUNT';
